"""
Django settings for mr_delivery project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ[key] = value


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ks(3+a!y^q!)8ui6apqlqk0@a7i7k_!7k2)l1bdmf%n(6ekv0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mrdelivery.pythonanywhere.com', '86.48.3.103', 'localhost', '127.0.0.1']


CSRF_TRUSTED_ORIGINS = [
    "https://mrdelivery.pythonanywhere.com",
]


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default=None):
    value = os.environ.get(name)
    if value is None:
        return default
    value = value.strip()
    if not value:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


# CORS
# NOTE: `file://` pages send Origin as `null`; keep this enabled only for local testing.
_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG and not CORS_ALLOWED_ORIGINS)
CORS_ALLOW_NULL_ORIGIN = _env_bool("CORS_ALLOW_NULL_ORIGIN", default=DEBUG)
CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", default=False)
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = [
    "Authorization",
    "Content-Type",
    "Accept",
    "Origin",
    "X-Requested-With",
    "X-CSRFToken",
    "Accept-Language",
]
CORS_PREFLIGHT_MAX_AGE = int(os.environ.get("CORS_PREFLIGHT_MAX_AGE", "86400"))


# Application definition

INSTALLED_APPS = [
    'daphne',  # يجب أن يكون أولاً
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'admin_desktop_app',
    'shop_app',
    'driver_app',
    'customer_app',
    'support_center',
    'platform_core',
    'user',
    'gallery',
    'shop',

]

MIDDLEWARE = [
    'user.middleware.StripUntrustedOriginSecurityHeadersMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'user.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'user.middleware.APILanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# We intentionally serve some dashboard screens over plain HTTP on raw IPs.
# Disable Django's default COOP header there to avoid browser warnings.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

ROOT_URLCONF = 'mr_delivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mr_delivery.wsgi.application'
ASGI_APPLICATION = 'mr_delivery.asgi.application'

# Channels settings
# IMPORTANT:
# - محليًا (بدون Redis): استخدم InMemoryChannelLayer
# - على السيرفر: استخدم RedisChannelLayer عبر متغيرات البيئة
#
# لتشغيل Redis محليًا:
# set REDIS_URL=redis://127.0.0.1:6379/0
# أو على Linux/macOS:
# export REDIS_URL=redis://127.0.0.1:6379/0
#
# على PythonAnywhere (مدفوع عادة): استخدم REDIS_URL التي يوفرها لك PythonAnywhere.

REDIS_URL = os.environ.get("REDIS_URL", "").strip()

if REDIS_URL:
    # استخدام Redis من متغير البيئة (للسيرفر)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
elif os.environ.get('DJANGO_ENV') == 'production' or '86.48.3.103' in ALLOWED_HOSTS:
    # على VPS: استخدام Redis محلي
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [('127.0.0.1', 6379)],
            },
        },
    }
else:
    # محليًا: استخدام InMemory
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Media files (Images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', '').strip().rstrip('/')

# Public app splash status / maintenance mode
APP_STATUS_MAINTENANCE_MODE = _env_bool("APP_STATUS_MAINTENANCE_MODE", default=False)
APP_STATUS_MAINTENANCE_TITLE_AR = os.environ.get(
    "APP_STATUS_MAINTENANCE_TITLE_AR",
    "التطبيق تحت الصيانة حاليًا",
).strip()
APP_STATUS_MAINTENANCE_TITLE_EN = os.environ.get(
    "APP_STATUS_MAINTENANCE_TITLE_EN",
    "The app is currently under maintenance",
).strip()
APP_STATUS_MAINTENANCE_MESSAGE_AR = os.environ.get(
    "APP_STATUS_MAINTENANCE_MESSAGE_AR",
    "نقوم الآن بتنفيذ تحديثات وتحسينات مهمة. نعتذر عن الإزعاج وسيعود التطبيق قريبًا.",
).strip()
APP_STATUS_MAINTENANCE_MESSAGE_EN = os.environ.get(
    "APP_STATUS_MAINTENANCE_MESSAGE_EN",
    "We are applying important updates and improvements. Sorry for the interruption.",
).strip()
APP_STATUS_MAINTENANCE_WINDOW_LABEL_AR = os.environ.get(
    "APP_STATUS_MAINTENANCE_WINDOW_LABEL_AR",
    "",
).strip()
APP_STATUS_MAINTENANCE_WINDOW_LABEL_EN = os.environ.get(
    "APP_STATUS_MAINTENANCE_WINDOW_LABEL_EN",
    "",
).strip()
APP_STATUS_SHOW_CONTACT_SUPPORT = _env_bool("APP_STATUS_SHOW_CONTACT_SUPPORT", default=False)
APP_STATUS_SUPPORT_WHATSAPP = os.environ.get("APP_STATUS_SUPPORT_WHATSAPP", "").strip()
APP_STATUS_ESTIMATED_MINUTES = _env_int("APP_STATUS_ESTIMATED_MINUTES", default=None)
APP_STATUS_FORCE_UPDATE_ENABLED = _env_bool("APP_STATUS_FORCE_UPDATE_ENABLED", default=False)
APP_STATUS_FORCE_UPDATE_CURRENT_VERSION = os.environ.get(
    "APP_STATUS_FORCE_UPDATE_CURRENT_VERSION",
    "",
).strip()
APP_STATUS_FORCE_UPDATE_REQUIRED_VERSION = (
    os.environ.get("APP_STATUS_FORCE_UPDATE_REQUIRED_VERSION", "").strip()
    or APP_STATUS_FORCE_UPDATE_CURRENT_VERSION
)

# Firebase Cloud Messaging (FCM)
_DEFAULT_FCM_SERVICE_ACCOUNT_CANDIDATES = [
    BASE_DIR / "zaygo-captains-firebase-adminsdk-fbsvc-54aab8b36c.json",
    BASE_DIR / "zaygo-user-firebase-adminsdk-fbsvc-fc21d26812.json",
]
DEFAULT_FCM_SERVICE_ACCOUNT_FILE = next(
    (path for path in _DEFAULT_FCM_SERVICE_ACCOUNT_CANDIDATES if path.exists()),
    _DEFAULT_FCM_SERVICE_ACCOUNT_CANDIDATES[0],
)
FCM_SERVICE_ACCOUNT_FILE = os.environ.get(
    "FCM_SERVICE_ACCOUNT_FILE",
    str(DEFAULT_FCM_SERVICE_ACCOUNT_FILE if DEFAULT_FCM_SERVICE_ACCOUNT_FILE.exists() else ""),
).strip()
FCM_SERVICE_ACCOUNT_JSON = os.environ.get("FCM_SERVICE_ACCOUNT_JSON", "").strip()
FCM_PROJECT_ID = os.environ.get("FCM_PROJECT_ID", "").strip()
FCM_ENABLED = _env_bool(
    "FCM_ENABLED",
    default=bool(FCM_SERVICE_ACCOUNT_FILE or FCM_SERVICE_ACCOUNT_JSON),
)
FCM_RING_CHANNEL_ID = os.environ.get("FCM_RING_CHANNEL_ID", "incoming_ring_channel").strip() or "incoming_ring_channel"
FCM_CHAT_CHANNEL_ID = os.environ.get("FCM_CHAT_CHANNEL_ID", "chat_channel").strip() or "chat_channel"
FCM_RING_SOUND = os.environ.get("FCM_RING_SOUND", "incoming_call").strip() or "incoming_call"
FCM_RING_IOS_SOUND = os.environ.get("FCM_RING_IOS_SOUND", "incoming_call.mp3").strip() or "incoming_call.mp3"
FCM_CHAT_SOUND = os.environ.get("FCM_CHAT_SOUND", "default").strip() or "default"
FCM_CHAT_IOS_SOUND = os.environ.get("FCM_CHAT_IOS_SOUND", "default").strip() or "default"

FCM_DRIVER_URGENT_CHANNEL_ID = (
    os.environ.get("FCM_DRIVER_URGENT_CHANNEL_ID", "delivery_orders_urgent").strip()
    or "delivery_orders_urgent"
)
FCM_DRIVER_GENERAL_CHANNEL_ID = (
    os.environ.get("FCM_DRIVER_GENERAL_CHANNEL_ID", "delivery_general").strip()
    or "delivery_general"
)
FCM_DRIVER_ORDER_SOUND = os.environ.get("FCM_DRIVER_ORDER_SOUND", "order_ring").strip() or "order_ring"
FCM_DRIVER_ORDER_IOS_SOUND = os.environ.get("FCM_DRIVER_ORDER_IOS_SOUND", "order_ring.mp3").strip() or "order_ring.mp3"
FCM_DRIVER_DEFAULT_SOUND = os.environ.get("FCM_DRIVER_DEFAULT_SOUND", "default").strip() or "default"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.ShopOwnerJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'shop.core.permissions.EnsureActiveAccountPermission',
        'shop.core.permissions.MaintenanceModePermission',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'EXCEPTION_HANDLER': 'user.exceptions.custom_exception_handler',
}

# OTP: رمز ثابت حتى الاشتراك في خدمة إرسال (واتساب/UltraMsg)
# إذا كان معيّناً يُستخدم هذا الرمز لجميع الطلبات ولا يُرسل أي OTP فعلي
FIXED_OTP_CODE = os.environ.get("FIXED_OTP_CODE", "").strip()

# UltraMsg (WhatsApp OTP) - يُستخدم فقط عندما FIXED_OTP_CODE فارغ
ULTRAMSG_INSTANCE = os.environ.get("ULTRAMSG_INSTANCE", "instance160549")
ULTRAMSG_TOKEN = os.environ.get("ULTRAMSG_TOKEN", "9l9mdphqnkcnuhf0")

# Email (Gmail SMTP) for customer OTP
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER).strip()

# Cache (for OTP storage - uses Redis if available, else local memory)
_CACHE_REDIS = os.environ.get("REDIS_URL", "").strip()
if _CACHE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _CACHE_REDIS,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "otp-cache",
        }
    }

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}
