[program:mr_delivery_daphne]
command=/home/Mr_Delivery/venv/bin/daphne -b 127.0.0.1 -p 8000 mr_delivery.asgi:application
directory=/home/Mr_Delivery
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/mr_delivery/daphne.log
stderr_logfile=/var/log/mr_delivery/daphne_error.log
environment=DJANGO_SETTINGS_MODULE="mr_delivery.settings",DJANGO_ENV="production"
