# Generated by Django 6.0.1 on 2026-01-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], default='draft', max_length=20, verbose_name='الحالة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('likes_count', models.IntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'صورة المعرض',
                'verbose_name_plural': 'صور المعرض',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=100, verbose_name='معرف المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.galleryimage', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجابات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.CharField(default='الأحد - الخميس', max_length=100, verbose_name='أيام العمل')),
                ('work_hours', models.CharField(default='9:00 صباحاً - 5:00 مساءً', max_length=50, verbose_name='ساعات العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'مواعيد العمل',
                'verbose_name_plural': 'مواعيد العمل',
            },
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['shop_owner', 'status'], name='gallery_gal_shop_ow_acace4_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['-uploaded_at'], name='gallery_gal_uploade_12a514_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagelike',
            unique_together={('image', 'user_identifier')},
        ),
    ]
