# Generated by Django 6.0.1 on 2026-01-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_shopowner_profile_image_delete_shopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customer_profiles/', verbose_name='صورة العميل')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل الآن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='driver_profiles/', verbose_name='صورة السائق')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('busy', 'مشغول'), ('offline', 'غير متصل')], default='offline', max_length=20, verbose_name='الحالة')),
                ('current_orders_count', models.IntegerField(default=0, verbose_name='عدد الطلبات الحالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التحضير'), ('on_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب')),
                ('items', models.TextField(verbose_name='الأصناف')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('address', models.TextField(verbose_name='العنوان الكامل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('unread_messages_count', models.IntegerField(default=0, verbose_name='عدد الرسائل غير المقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.customer', verbose_name='العميل')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.driver', verbose_name='السائق')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('items', models.TextField(verbose_name='الأصناف')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('address', models.TextField(verbose_name='العنوان الكامل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shop.customer', verbose_name='العميل')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='user.shopowner', verbose_name='صاحب المحل')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='shop.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'عميل'), ('shop', 'المحل')], max_length=20, verbose_name='نوع المرسل')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('audio', 'صوت'), ('image', 'صورة')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/', verbose_name='ملف صوتي')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='صورة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('busy', 'مشغول'), ('closed', 'مغلق')], default='closed', max_length=20, verbose_name='الحالة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_status', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'حالة المتجر',
                'verbose_name_plural': 'حالات المتاجر',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop_owner', '-updated_at'], name='shop_custom_shop_ow_476176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('shop_owner', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['shop_owner', 'status'], name='shop_driver_shop_ow_9be37c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop_owner', 'status'], name='shop_order_shop_ow_e70241_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop_owner', '-created_at'], name='shop_order_shop_ow_92526c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop_owner', '-created_at'], name='shop_invoic_shop_ow_6af91d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['order', 'created_at'], name='shop_chatme_order_i_7974d7_idx'),
        ),
    ]
