# Generated by Django 6.0.1 on 2026-01-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('user', '0003_add_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.IntegerField(default=0, verbose_name='إجمالي الرحلات'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('pending', 'طلب انضمام'), ('available', 'متاح'), ('busy', 'مشغول'), ('offline', 'غير متصل')], default='available', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('shop_owner', 'phone_number')},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('role', models.CharField(choices=[('cashier', 'كاشير'), ('accountant', 'محاسب'), ('supervisor', 'مشرف عمليات'), ('customer_service', 'خدمة عملاء'), ('sales', 'مندوب مبيعات'), ('hr', 'موارد بشرية'), ('manager', 'مدير فرع')], default='cashier', max_length=50, verbose_name='الدور')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employee_profiles/', verbose_name='صورة الموظف')),
                ('custody_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ في العهدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_handled', to='shop.employee', verbose_name='الموظف المسؤول'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصنف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='صورة الصنف')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'قائمة المنتجات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['shop_owner', 'role'], name='shop_employ_shop_ow_75406b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['shop_owner', 'is_active'], name='shop_employ_shop_ow_4a8d40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('shop_owner', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop_owner', 'is_available'], name='shop_produc_shop_ow_54c72e_idx'),
        ),
    ]
