# Generated by Django 6.0.1 on 2026-01-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_custody_employee_order_products_driver_pending'),
        ('user', '0003_add_shop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سلة تسوق',
                'verbose_name_plural': 'سلات التسوق',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عنصر السلة',
                'verbose_name_plural': 'عناصر السلة',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='صورة التصنيف')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مختصر')),
                ('address_type', models.CharField(choices=[('home', 'المنزل'), ('work', 'العمل'), ('other', 'أخرى')], default='home', max_length=20, verbose_name='نوع العنوان')),
                ('full_address', models.TextField(verbose_name='العنوان الكامل')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('building_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المبنى')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='الطابق')),
                ('apartment', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشقة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'عنوان عميل',
                'verbose_name_plural': 'عناوين العملاء',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'حالة الطلب'), ('promotion', 'عرض'), ('system', 'النظام'), ('chat', 'محادثة')], default='system', max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_rating', models.PositiveSmallIntegerField(help_text='من 1 إلى 5', verbose_name='تقييم المحل')),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, help_text='من 1 إلى 5', null=True, verbose_name='تقييم السائق')),
                ('food_rating', models.PositiveSmallIntegerField(blank=True, help_text='من 1 إلى 5', null=True, verbose_name='تقييم الطعام')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='تعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
            ],
            options={
                'verbose_name': 'تقييم طلب',
                'verbose_name_plural': 'تقييمات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('mada', 'مدى'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay')], max_length=20, verbose_name='نوع البطاقة')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='آخر 4 أرقام')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='اسم حامل البطاقة')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='شهر الانتهاء')),
                ('expiry_year', models.CharField(max_length=4, verbose_name='سنة الانتهاء')),
                ('is_default', models.BooleanField(default=False, verbose_name='البطاقة الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='shop_custom_shop_ow_476176_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض الحالي'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول الحالي'),
        ),
        migrations.AddField(
            model_name='driver',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم الفعلي'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الوقت المتوقع للتوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً عند الاستلام'), ('card', 'بطاقة ائتمان'), ('wallet', 'محفظة إلكترونية')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بعد الخصم'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='user.shopowner', verbose_name='صاحب المحل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التحضير'), ('on_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-updated_at'], name='shop_custom_updated_16b515_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='shop_custom_phone_n_4a032a_idx'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shop_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.shopowner', verbose_name='المحل'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='السلة'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='category',
            name='shop_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user.shopowner', verbose_name='صاحب المحل'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='التصنيف'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='shop_produc_categor_d249e3_idx'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.customeraddress', verbose_name='عنوان التوصيل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.driver', verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='notification',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.shopowner', verbose_name='صاحب المحل'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='orderrating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='shop.customer', verbose_name='العميل'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'shop_owner')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer', '-created_at'], name='shop_notifi_custome_50905e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop_owner', '-created_at'], name='shop_notifi_shop_ow_1d8452_idx'),
        ),
    ]
