# Generated by Django 6.0.1 on 2026-01-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_all_missing_features'),
        ('user', '0003_add_shop_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='shop_chatme_order_i_7974d7_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_type',
            field=models.CharField(choices=[('shop_customer', 'محادثة المحل مع العميل'), ('driver_customer', 'محادثة السائق مع العميل')], default='shop_customer', max_length=20, verbose_name='نوع المحادثة'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='shop.customer', verbose_name='العميل المرسل'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='shop.driver', verbose_name='السائق المرسل'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='shop.employee', verbose_name='الموظف المرسل'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='user.shopowner', verbose_name='صاحب المحل المرسل'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى الرسالة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'نص'), ('audio', 'صوت'), ('image', 'صورة'), ('location', 'موقع')], default='text', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('shop_owner', 'صاحب المحل'), ('employee', 'موظف'), ('driver', 'سائق')], max_length=20, verbose_name='نوع المرسل'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['order', 'chat_type', 'created_at'], name='shop_chatme_order_i_9fa59c_idx'),
        ),
    ]
