# Generated by Django 6.0.1 on 2026-02-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_update_chat_message_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('pending_customer_confirm', 'في انتظار تأكيد العميل'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التحضير'), ('on_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=32, verbose_name='حالة الطلب'),
        ),
    ]
