# Generated by Django 6.0.1 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_driver_vehicle_type_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور'),
        ),
        migrations.CreateModel(
            name='CustomerPresenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True, verbose_name='اسم القناة')),
                ('connection_type', models.CharField(default='websocket', max_length=50, verbose_name='نوع الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_connections', to='shop.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'اتصال حضور العميل',
                'verbose_name_plural': 'اتصالات حضور العميل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerpresenceconnection',
            index=models.Index(fields=['customer', '-created_at'], name='shop_custom_custome_2b74ce_idx'),
        ),
    ]
