# Generated by Django 6.0.1 on 2026-01-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='اسم صاحب المحل')),
                ('shop_name', models.CharField(max_length=100, verbose_name='اسم المحل')),
                ('shop_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المحل')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صاحب المحل',
                'verbose_name_plural': 'أصحاب المحلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/', verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.shopowner', verbose_name='صاحب المحل')),
            ],
            options={
                'verbose_name': 'صورة المحل',
                'verbose_name_plural': 'صور المحلات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
