# Generated by Django 6.0.1 on 2026-01-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_profiles/', verbose_name='صورة البروفيل'),
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
