# Generated by Django 6.0.1 on 2026-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_shopowner_profile_image_delete_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المحل'),
        ),
    ]
