# Generated by Django 6.0.1 on 2026-04-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_shopowner_profile_image_delete_shopimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDesktopUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="اسم المستخدم")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="رقم الهاتف")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني")),
                ("password", models.CharField(max_length=128, verbose_name="كلمة المرور")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("dashboard_manager", "مدير النظام"),
                            ("system_developer", "مطور النظام"),
                        ],
                        max_length=50,
                        verbose_name="الدور",
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list, verbose_name="الصلاحيات")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="admin_desktop_profiles/",
                        verbose_name="صورة المستخدم",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("last_login_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر تسجيل دخول")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث")),
            ],
            options={
                "verbose_name": "مستخدم الديسكتوب",
                "verbose_name_plural": "مستخدمو الديسكتوب",
                "ordering": ["-created_at"],
            },
        ),
    ]
