# Generated by Django 6.0.1 on 2026-01-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
