# Generated by Django 6.0.1 on 2026-02-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_shop_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='shop_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='تصنيف المحل'),
        ),
    ]
