# Generated by Django 6.0.1 on 2026-02-14 20:22

import django.db.models.deletion
from django.db import migrations, models


def copy_shop_category_to_fk(apps, schema_editor):
    ShopOwner = apps.get_model('user', 'ShopOwner')
    ShopCategory = apps.get_model('user', 'ShopCategory')

    for owner in ShopOwner.objects.exclude(shop_category__isnull=True).exclude(shop_category__exact=''):
        category_name = (owner.shop_category or '').strip()
        if not category_name:
            continue
        category, _ = ShopCategory.objects.get_or_create(name=category_name)
        owner.shop_category_fk_id = category.id
        owner.save(update_fields=['shop_category_fk'])


def copy_shop_category_to_text(apps, schema_editor):
    ShopOwner = apps.get_model('user', 'ShopOwner')
    ShopCategory = apps.get_model('user', 'ShopCategory')

    category_by_id = {c.id: c.name for c in ShopCategory.objects.all()}
    for owner in ShopOwner.objects.exclude(shop_category_fk__isnull=True):
        owner.shop_category = category_by_id.get(owner.shop_category_fk_id, '')
        owner.save(update_fields=['shop_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_shopowner_shop_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف محل',
                'verbose_name_plural': 'تصنيفات المحلات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shop_category_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shops',
                to='user.shopcategory',
                verbose_name='تصنيف المحل',
            ),
        ),
        migrations.RunPython(copy_shop_category_to_fk, copy_shop_category_to_text),
        migrations.RemoveField(
            model_name='shopowner',
            name='shop_category',
        ),
        migrations.RenameField(
            model_name='shopowner',
            old_name='shop_category_fk',
            new_name='shop_category',
        ),
    ]
