# Generated by Django 6.0.1 on 2026-02-26 00:00

from django.db import migrations, models


def default_work_schedule():
    return {
        'saturday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'sunday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'monday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'tuesday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'wednesday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'thursday': {'is_working': True, 'start_time': '09:00', 'end_time': '17:00'},
        'friday': {'is_working': False, 'start_time': None, 'end_time': None},
    }


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_shopcategory_alter_shopowner_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='work_schedule',
            field=models.JSONField(blank=True, default=default_work_schedule, verbose_name='مواعيد العمل الأسبوعية'),
        ),
    ]
